use engram_embeddings::cache::EmbeddingCache;
use engram_embeddings::embedder::Embedder;
use engram_embeddings::error::EmbeddingError;
use engram_embeddings::hyde;
use engram_llm_client::error::ApiError;
use engram_llm_client::provider::{EmbeddingProvider, TextGenerator};

// ── Mock providers ─────────────────────────────────────────────────────

struct MockEmbeddingProvider {
    dimension: usize,
}

impl EmbeddingProvider for MockEmbeddingProvider {
    fn embed(&self, text: &str) -> Result<Vec<f32>, ApiError> {
        let mut embedding = vec![0.0_f32; self.dimension];
        for (index, byte) in text.bytes().enumerate() {
            embedding[index % self.dimension] += byte as f32 / 255.0;
        }
        Ok(embedding)
    }

    fn dimension(&self) -> usize {
        self.dimension
    }

    fn model_name(&self) -> &str {
        "mock-embedding"
    }
}

struct FailingEmbeddingProvider;

impl EmbeddingProvider for FailingEmbeddingProvider {
    fn embed(&self, _text: &str) -> Result<Vec<f32>, ApiError> {
        Err(ApiError::EmbeddingApiUnavailable("mock failure".into()))
    }

    fn dimension(&self) -> usize {
        128
    }

    fn model_name(&self) -> &str {
        "failing-embedding"
    }
}

struct MockTextGenerator {
    response: String,
}

impl TextGenerator for MockTextGenerator {
    fn generate(&self, _prompt: &str) -> Result<String, ApiError> {
        Ok(self.response.clone())
    }

    fn model_name(&self) -> &str {
        "mock-generator"
    }
}

struct FailingTextGenerator;

impl TextGenerator for FailingTextGenerator {
    fn generate(&self, _prompt: &str) -> Result<String, ApiError> {
        Err(ApiError::HyDeGenerationFailed(
            "mock generation failure".into(),
        ))
    }

    fn model_name(&self) -> &str {
        "failing-generator"
    }
}

// ── embed_fields ───────────────────────────────────────────────────────

#[test]
fn embed_fields_returns_three_embeddings() {
    let provider = MockEmbeddingProvider { dimension: 4 };
    let mut embedder = Embedder::new();

    let result = embedder
        .embed_fields(
            "user opened the editor and started typing a document",
            "typed a paragraph about rust programming language features",
            "the document was saved successfully to the local filesystem",
            &provider,
            None,
        )
        .unwrap();

    assert_eq!(result.context.len(), 4);
    assert_eq!(result.action.len(), 4);
    assert_eq!(result.result.len(), 4);
}

#[test]
fn embed_fields_caches_identical_text() {
    let provider = MockEmbeddingProvider { dimension: 4 };
    let mut embedder = Embedder::new();

    let same_text = "user opened the editor and started typing a long document about rust";

    embedder
        .embed_fields(same_text, same_text, same_text, &provider, None)
        .unwrap();

    assert_eq!(embedder.cache().len(), 1);
}

#[test]
fn embed_fields_different_texts_produce_different_embeddings() {
    let provider = MockEmbeddingProvider { dimension: 8 };
    let mut embedder = Embedder::new();

    let result = embedder
        .embed_fields(
            "user opened the editor window and began writing a new document from scratch",
            "typed several paragraphs about the rust programming language and its features",
            "the document was saved successfully to the local filesystem without any errors",
            &provider,
            None,
        )
        .unwrap();

    assert_ne!(result.context, result.action);
    assert_ne!(result.action, result.result);
    assert_ne!(result.context, result.result);
}

// ── embed_query ────────────────────────────────────────────────────────

#[test]
fn embed_query_returns_single_embedding() {
    let provider = MockEmbeddingProvider { dimension: 4 };
    let mut embedder = Embedder::new();

    let long_query =
        "search for all documents that were created in the last week about rust programming";
    let result = embedder.embed_query(long_query, &provider, None).unwrap();

    assert_eq!(result.len(), 4);
}

#[test]
fn embed_query_uses_cache() {
    let provider = MockEmbeddingProvider { dimension: 4 };
    let mut embedder = Embedder::new();

    let query = "search for documents about rust programming language features and memory safety";

    let first = embedder.embed_query(query, &provider, None).unwrap();
    let second = embedder.embed_query(query, &provider, None).unwrap();

    assert_eq!(first, second);
    assert_eq!(embedder.cache().len(), 1);
}

// ── HyDE ───────────────────────────────────────────────────────────────

#[test]
fn hyde_triggered_for_short_text() {
    let provider = MockEmbeddingProvider { dimension: 4 };
    let generator = MockTextGenerator {
        response:
            "this is a hypothetical document generated by the text generator for short queries"
                .into(),
    };
    let mut embedder = Embedder::new();

    let short_query = "rust memory safety";

    embedder
        .embed_query(short_query, &provider, Some(&generator))
        .unwrap();

    // Cache should contain the hypothesis, not the raw query
    assert!(embedder.cache().get(short_query).is_none());
    assert!(embedder.cache().get(&generator.response).is_some());
}

#[test]
fn hyde_not_triggered_for_long_text() {
    let provider = MockEmbeddingProvider { dimension: 4 };
    let generator = MockTextGenerator {
        response:
            "hypothesis that should not be used because the input text is already long enough"
                .into(),
    };
    let mut embedder = Embedder::new();

    let long_text = "one two three four five six seven eight nine ten \
                     eleven twelve thirteen fourteen fifteen sixteen \
                     seventeen eighteen nineteen twenty";

    embedder
        .embed_query(long_text, &provider, Some(&generator))
        .unwrap();

    // Cache should contain the raw text, not the hypothesis
    assert!(embedder.cache().get(long_text).is_some());
    assert!(embedder.cache().get(&generator.response).is_none());
}

#[test]
fn hyde_failure_falls_back_to_raw_text() {
    let provider = MockEmbeddingProvider { dimension: 4 };
    let generator = FailingTextGenerator;
    let mut embedder = Embedder::new();

    let short_query = "rust memory";

    let result = embedder.embed_query(short_query, &provider, Some(&generator));

    assert!(result.is_ok());
    assert!(embedder.cache().get(short_query).is_some());
}

#[test]
fn hyde_without_text_generator_embeds_raw() {
    let provider = MockEmbeddingProvider { dimension: 4 };
    let mut embedder = Embedder::new();

    let short_query = "rust memory";

    let result = embedder.embed_query(short_query, &provider, None);

    assert!(result.is_ok());
    assert!(embedder.cache().get(short_query).is_some());
}

// ── Error propagation ──────────────────────────────────────────────────

#[test]
fn provider_error_propagates() {
    let provider = FailingEmbeddingProvider;
    let mut embedder = Embedder::new();

    let long_text =
        "a sufficiently long text that will not trigger hyde generation at all for testing";
    let result = embedder.embed_query(long_text, &provider, None);

    assert!(result.is_err());
    let error = result.unwrap_err();
    assert!(
        matches!(error, EmbeddingError::ProviderError(_)),
        "expected ProviderError, got: {error}"
    );
}

// ── Cache ──────────────────────────────────────────────────────────────

#[test]
fn cache_clear_works() {
    let provider = MockEmbeddingProvider { dimension: 4 };
    let mut embedder = Embedder::new();

    let query = "search for documents about rust programming and its unique memory safety features";

    embedder.embed_query(query, &provider, None).unwrap();
    assert_eq!(embedder.cache().len(), 1);

    embedder.clear_cache();
    assert!(embedder.cache().is_empty());

    // Re-embedding should work after cache clear
    embedder.embed_query(query, &provider, None).unwrap();
    assert_eq!(embedder.cache().len(), 1);
}

#[test]
fn cache_starts_empty() {
    let cache = EmbeddingCache::new();
    assert!(cache.is_empty());
    assert_eq!(cache.len(), 0);
}

// ── hyde module boundary tests ─────────────────────────────────────────

#[test]
fn should_use_hyde_boundary() {
    // Exactly 20 words -> false
    let twenty_words = "one two three four five six seven eight nine ten \
                        eleven twelve thirteen fourteen fifteen sixteen \
                        seventeen eighteen nineteen twenty";
    assert!(!hyde::should_use_hyde(twenty_words));
}

#[test]
fn should_use_hyde_under_threshold() {
    // 19 words -> true
    let nineteen_words = "one two three four five six seven eight nine ten \
                          eleven twelve thirteen fourteen fifteen sixteen \
                          seventeen eighteen nineteen";
    assert!(hyde::should_use_hyde(nineteen_words));
}

// ── EmbeddingError ─────────────────────────────────────────────────────

#[test]
fn embedding_error_display_format() {
    let provider_error =
        EmbeddingError::ProviderError(ApiError::EmbeddingApiUnavailable("timeout".into()));
    assert_eq!(
        provider_error.to_string(),
        "embedding provider error: [2001] embedding api unavailable: timeout"
    );
}

#[test]
fn embedding_error_from_api_error() {
    let api_error = ApiError::EmbeddingApiUnavailable("connection lost".into());
    let embedding_error: EmbeddingError = api_error.into();

    assert!(matches!(embedding_error, EmbeddingError::ProviderError(_)));
    assert_eq!(
        embedding_error.to_string(),
        "embedding provider error: [2001] embedding api unavailable: connection lost"
    );
}

// ── embed_fields with failing text generator ──────────────────────────

#[test]
fn embed_fields_with_failing_generator_falls_back_to_raw_text() {
    let provider = MockEmbeddingProvider { dimension: 4 };
    let generator = FailingTextGenerator;
    let mut embedder = Embedder::new();

    let result = embedder.embed_fields(
        "rust memory",
        "open editor",
        "saved file",
        &provider,
        Some(&generator),
    );

    assert!(result.is_ok());
    let embedding = result.unwrap();
    assert_eq!(embedding.context.len(), 4);
    assert_eq!(embedding.action.len(), 4);
    assert_eq!(embedding.result.len(), 4);
}

// ── Error::source() ───────────────────────────────────────────────────

#[test]
fn embedding_error_source_returns_underlying_api_error() {
    use std::error::Error;

    let api_error = ApiError::EmbeddingApiUnavailable("connection reset".into());
    let embedding_error = EmbeddingError::ProviderError(api_error);

    let source = embedding_error.source();
    assert!(source.is_some());
    assert!(source.unwrap().to_string().contains("connection reset"));
}

// ── Default trait impls ───────────────────────────────────────────────

#[test]
fn embedder_default_has_empty_cache() {
    let embedder = Embedder::default();
    assert!(embedder.cache().is_empty());
}

#[test]
fn embedding_cache_default_is_empty() {
    let cache = EmbeddingCache::default();
    assert!(cache.is_empty());
    assert_eq!(cache.len(), 0);
}

// ── embed_fields with HyDE ───────────────────────────────────────────

#[test]
fn embed_fields_with_hyde_uses_hypothesis_for_short_text() {
    let provider = MockEmbeddingProvider { dimension: 4 };
    let generator = MockTextGenerator {
        response:
            "this is a hypothetical document generated by the text generator for short fields"
                .into(),
    };
    let mut embedder = Embedder::new();

    let short_context = "rust memory";
    let short_action = "open editor";
    let short_result = "saved file";

    let result = embedder.embed_fields(
        short_context,
        short_action,
        short_result,
        &provider,
        Some(&generator),
    );

    assert!(result.is_ok());
    // All short fields should trigger HyDE and resolve to the same hypothesis
    assert!(embedder.cache().get(&generator.response).is_some());
    assert!(embedder.cache().get(short_context).is_none());
    assert!(embedder.cache().get(short_action).is_none());
    assert!(embedder.cache().get(short_result).is_none());
}
